### PR TITLE
Update accounts and curriculum

### PR DESCRIPTION
**Pull request by feliciofilipe**

### CODE REVIEW

**Review by ruioliveira02 — CHANGES_REQUESTED** [review]
Creating a new account does not work for any role (editing is fine)
Make sure CI passes (run format and linter) :pray:

**Review by laraujo7 — CHANGES_REQUESTED** [review]
The server is crashing when you try to delete a company, and a job offer. Also, ensure you handle the error when deleting a job offer that attendees have applied.

Screenshot 2022-06-16 at 23 08 01

Additionally, on every page, we usually put the page's title.
Screenshot 2022-06-16 at 23 09 11

**Comment by laraujo7** [comment]
For the love of God, don't forget to pull before pushing force 🙏

**Review by laraujo7 — APPROVED** [review]
🚀🚀🚀🚀🚀

**Pull request merged**
